


cache: kafka

kafka:
    # ip: 'broker'
    # port: 29092
    ip: '203.245.29.236' 
    port: 9092
    # schema_registry_ip: 'schema-registry'
    schema_registry_ip: '203.245.29.236'
    schema_registry_port: 8081
    topic_key: 'loopyquant01.01'
    start_flush: false
redis:
    ip: '127.0.0.1'
    port: 6379
    socket: null
    del_after_read: true
    retention_time: null
    start_flush: true

# exchanges:
#     BINANCE_FUTURES:
#         trades: [BTC-USDT-PERP, ETH-USDT-PERP, ADA-USDT-PERP, LUNA-USDT-PERP, BNB-USD-PERP]
#         ticker: [BTC-USDT-PERP, ETH-USDT-PERP, ADA-USDT-PERP, LUNA-USDT-PERP, BNB-USD-PERP]
#         funding: [BTC-USDT-PERP, ETH-USDT-PERP, ADA-USDT-PERP, LUNA-USDT-PERP, BNB-USD-PERP]
#         balances: []
#         positions: []
#         order_info: [] 
#     BINANCE_DELIVERY:
#         trades: [BTC-USD-PERP, ETH-USD-PERP, ADA-USD-PERP, LUNA-USD-PERP, BNB-USD-PERP]
#         ticker: [BTC-USD-PERP, ETH-USD-PERP, ADA-USD-PERP, LUNA-USD-PERP, BNB-USD-PERP]
#         funding: [BTC-USD-PERP, ETH-USD-PERP, ADA-USD-PERP, LUNA-USD-PERP, BNB-USD-PERP]
#         balances: []
#         positions: []
#         order_info: [] 

# Cryptostore Plugin Interface
# plugins:
    # trend_macd_strategy:
    #     module: [cryptostore.strategy.trend_macd_strategy, TrendMACDStrategy]
    #     config: sandbox/strategy_config.yaml 
    # market_info_feed:
    #     module: [cryptostore.strategy.market_info_feed, MarketInfoFeed]
    #     config: sandbox/strategy_config.yaml 
