# Cryptostore sample backfil config file

# Cryptostore Plugin Interface
# plugins:
#     backfill:
#         # The import path, and class name
#         # from cryptostore.plugin.backfill import Backfill
#        module: [cryptostore.plugin.backfill, Backfill]
#         # Config path, config can be added to this file, or in a separate config
#         # backfill does not use a dynamic config, so its fine to put its config here
#        config: config.yaml

# If configured, backfill will run in a separate process and
# backfill trade data from earliest data (in storage) up to `start` (inclusive).
# backfill:
#    BITMEX:
#        XBTUSD:
#            start: '2017-01-01'
    # COINBASE:
    #     BTC-USD:
    #         start: '2017-01-01'

restfeed:
    BINANCE_DELIVERY:
        BTC-USD_PERP:
            start: '2017-01-01'