version: "3.7"
services:
  # cryptostore:
  service:
    env_file:
      - env.s3config
    logging:
      driver: "json-file"
      options:
        max-size: "2000k"
        max-file: "10"
    build:
      context: .
      dockerfile: Dockerfile
    # if loopyluffy_default network exists... if not delete this setting... @logan
    # networks:
    #   - loopyluffy_default

  # redisdb:
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "2000k"
  #       max-file: "10"
  #   image: redis:6.0.8
  #   expose:
  #     - 6379
  #   command: ["redis-server", "--save", "''", "--appendonly", "no"]
  # mongo:
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "2000k"
  #       max-file: "10"
  #   container_name: mongo
  #   image: mongo:4.4.1-bionic
  #   ports:
  #     - '37017:27017'
  #   expose:
  #     - 27017

  # if external docker network exists... if not delete this setting... @logan
  # networks:
  #   loopyluffy_default:
  #     external: true
